### ISSUE TITLE
телеграм забанил на час

### ISSUE THREAD

**Issue by levksenya** [Babulekh/tgPostExporter#4]
Ошибка при сборе поста: https://t.me/donbassinfograd/112369
server.js:243
FloodWaitError: A wait of 2129 seconds is required (caused by contacts.ResolveUsername)
    at RPCMessageToError (/Users/ksenialev/5_ИнтерРАО/tgPostExporter/backend/node_modules/.pnpm/telegram@2.19.10/node_modules/telegram/errors/index.js:25:20)
    at MTProtoSender._handleRPCResult (/Users/ksenialev/5_ИнтерРАО/tgPostExporter/backend/node_modules/.pnpm/telegram@2.19.10/node_modules/telegram/network/MTProtoSender.js:537:58)
    at MTProtoSender._processMessage (/Users/ksenialev/5_ИнтерРАО/tgPostExporter/backend/node_modules/.pnpm/telegram@2.19.10/node_modules/telegram/network/MTProtoSender.js:467:15)
    at process.processTicksAndRejections (/Users/ksenialev/5_ИнтерРАО/tgPostExporter/backend/lib/internal/process/task_queues.js:95:5)
    at async MTProtoSender._recvLoop (/Users/ksenialev/5_ИнтерРАО/tgPostExporter/backend/node_modules/.pnpm/telegram@2.19.10/node_modules/telegram/network/MTProtoSender.js:418:17) {code: 420, errorMessage: 'FLOOD', seconds: 2129, stack: 'FloodWaitError: A wait of 2129 seconds is req…les/telegram/network/MTProtoSender.js:418:17)', message: 'A wait of 2129 seconds is required (caused by contacts.ResolveUsername)', …}

telegram.js:86

**Comment by levksenya** [comment]
Почему-то в `settings.json` `apiHash` в момент запуска сервера заменяется на `apiId`
```
  "apiId": "22469384",
  "apiHash": "22469384"
```
